version: '3.9'

services:
  pgv_emb_app:
    image: pgvector/pgvector:pg17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: my_emb_db
    ports:
      - "5432:5432"
    volumes:
      - ./app2_db.sql:/docker-entrypoint-initdb.d/app2_db.sql


  fastapi_app2: 
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - pgv_emb_app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:password@pgv_emb_app:5432/my_emb_db

  gradio_app2:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["python", "app2_front.py"]
    ports:
      - "7860:7860"
    depends_on:
      - fastapi_app2