version: '3.9'

services:
  my_pgv_app:
    image: pgvector/pgvector:pg17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: my_db
    ports:
      - "5432:5432"
    volumes:
      - ./my_app_db.sql:/docker-entrypoint-initdb.d/my_app_db.sql


  fastapi_app: 
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - my_pgv_app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:password@my_pgv_app:5432/my_db

  gradio_app:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["python", "my_app_front.py"]
    ports:
      - "7860:7860"
    depends_on:
      - fastapi_app