version: "3.9"
services:
  my_pg:
    image: postgres:17
    ports:
      - "5432:5432"  # Порт 5432 открыт для доступа извне
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: my_db  # Имя базы данных
  fastapi_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      
    depends_on:
      - my_pg
  gradio_app:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["python", "my_app_front.py"]
    ports:
      - "7860:7860"
    depends_on:
      - fastapi_app
    environment:
      DOCKER_ENV: 1
